name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Python version
        id: get-python-version
        run: |
          $pythonVersion = (Invoke-WebRequest -Uri "https://www.python.org/downloads/" -UseBasicParsing).Content -match 'Download Python (\d+\.\d+\.\d+)' | Out-Null; $matches[1]
          echo "::set-output name=python_version::${env:pythonVersion}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.get-python-version.outputs.python_version }}

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Install pipreqs
        run: pip install pipreqs

      - name: Generate requirements.txt
        run: |
          pipreqs --force .

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up UPX
        run: |
          choco install upx -y

      - name: Build EXE
        run: |
          pyinstaller cccam2oscam.spec

      - name: Create artifact
        run: |
          cd dist
          move cccam2oscam_*.exe ..

      - name: Save ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: cccam2oscam-win64
          path: cccam2oscam_*.exe
          
